### ISSUE TITLE
Note: Apparently the base game is a lil too base game, the mods ie: hat mod provide a sense of reality break, maybe in a reconsideration of how vanilla ,vanilla is, it doesn't feel like vanilla plus apparently

### ISSUE THREAD

**Issue by JonahLudiker** [JonahLudiker/GrindCraft-Rebuilt#5]
Look into quality of life/rose gold like stuff apparently?

**Comment by JonahLudiker** [comment]
@InBasilsGarden Can you provide further details - stage number, approx play time, submitter

**Comment by InBasilsGarden** [comment]
Stage Number, 0, approx playtime, 3 hours, delilah: She felt like there was in an expressionistic term, that the game wasn't as colorful, meaning that we lack variance in blocks, crops, and such to take up space, a field with no grass, if that makes sense.
